version: '3.9'

services:
  expensetracker:
    image: expensetracker:latest 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DATABASE=Host=postgres;Database=expensetracker;Username=postgres;Password=secret
      - CACHE__URL=valkey:6379
      - MASSTRANSIT__RABBITMQ__HOST=rabbitmq:5672  # Folosește RabbitMQ în loc de Kafka
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - postgres
      - valkey
      - rabbitmq

  valkey:
    image: valkey/valkey:latest 
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    environment:
      - VALKEY_MAXMEMORY=512mb 

  postgres:
    image: postgres:latest 
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expensetrackerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Portul pentru RabbitMQ
      - "15672:15672" # Portul pentru RabbitMQ Management Console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  valkey-data:
    driver: local
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
